### ISSUE TITLE
Discuss result

### ISSUE THREAD

**Issue by mawada-sweis** [mawada-sweis/Clustering-Analysis#24] opened 2023-02-28 20:00 UTC
Meet to discuss the clustering results for various algorithms and our progress.

**Comment by mawada-sweis** [comment] 2023-02-28 20:37
We _discuss_ the following issues at the meeting:
1. How to deal with 'date' columns.
2. Present the Elbow graph for the K-means and K-medoid algorithms and discuss the silhouette graphs and Clustering in 2-dimensions for each number of clusters (K) chosen (before PCA).
3. Present the KNN distance graph to select the optimal epsilon for the DBSCAN method and describe clustering in two dimensions for each suggested Epsilon and MinPoints (before and after PCA).
4. Present the Hierarchical algorithm's Dendrogram and discuss clustering in 2-dimension for each suggested K based on two cutting thresholds (before and after PCA).

We determine to do the following:
- [ ] Make the silhouette plot for each algorithm and compare the results. [tonight - @mawada-sweis @zubaidasader @Rama-Has ]
- [ ] Handling outlier. [tonight - @eleenkmail]
- [ ] based on the previous task, determine the best algorithm and best number of clusters. [tonight - for All]
- [ ] Extract the common features for each cluster after choosing the final algorithm. [Tomorow - @eleenkmail]
- [ ] Update the style of some codes. [Tomorow - @mawada-sweis @zubaidasader]
- [ ] Make the Report.  [Tomorow - for All]

**Comment by mawada-sweis** [comment] 2023-03-01 23:32
In the hierarchical model I use the dendrogram to choose best k, then I compare result between 3 and 4 clusters, and I found 4 clusters is the best.
@eleenkmail I share my data to use it in your task.

**Comment by eleenkmail** [comment] 2023-03-04 22:46
About handling outlier: considering statistical outliers as an outlier is subjective, because these values make sense with the feature meaning such as: 

Considering 175 as an outlier in "
Duplicate of #num_trips" column  because there are other close values around (100-125), and this outlier came from Staten Island which is the least populated borough but the third largest in land area atA home to the Lenape indigenous people.

**Closed** 2023-03-05 07:07 UTC
Labels: question
